version: "1.0"
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: mercury_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - mercury-net
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mercury_backend
    depends_on:
      - db
    networks:
      - mercury-net
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    restart: on-failure
  db:
    image: postgres:14-alpine
    container_name: mercury_db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mercury-net
    restart: always
networks:
  mercury-net:
    driver: bridge

volumes:
  db-data:
