# 全局块 (main context)
worker_processes 1;

# 为日志和 pid 文件提供完整的绝对路径
pid /home/losangelous/LosAngelous/Project/MercuryKV/logs/nginx.pid;
error_log /home/losangelous/LosAngelous/Project/MercuryKV/logs/error.log;

events {
    worker_connections 1024;
}

# HTTP 块
http {
    # 为所有临时文件提供完整的绝对路径
    client_body_temp_path /home/losangelous/LosAngelous/Project/MercuryKV/.nginx_dev_temp/client_body;
    proxy_temp_path       /home/losangelous/LosAngelous/Project/MercuryKV/.nginx_dev_temp/proxy;
    fastcgi_temp_path     /home/losangelous/LosAngelous/Project/MercuryKV/.nginx_dev_temp/fastcgi;
    uwsgi_temp_path       /home/losangelous/LosAngelous/Project/MercuryKV/.nginx_dev_temp/uwsgi;
    scgi_temp_path        /home/losangelous/LosAngelous/Project/MercuryKV/.nginx_dev_temp/scgi;

    server {
        listen 82;
        server_name localhost;

        location /api/ {
            rewrite ^/api(/.*)$ \$1 break;
            proxy_pass http://127.0.0.1:5555;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            # 代理到你的前端开发服务器
            proxy_pass http://127.0.0.1:5173; 
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
