# -----------------------------------------------------------------
# Drogon 应用程序配置文件 (YAML 格式)
# -----------------------------------------------------------------

#
# SSL/TLS 全局设置
# cert 和 key 分别是证书和私钥文件的路径。
#
ssl:
  cert: ""
  key: ""
  conf: []

#
# 监听器配置
# 可以配置多个监听器，比如一个用于 HTTP，一个用于 HTTPS。
#
listeners:
  - address: "0.0.0.0" # 监听所有网络接口
    port: 80           # HTTP 端口
    https: false       # 不启用 HTTPS

#
# 数据库客户端配置
# 可以配置连接到多个不同的数据库。
#
db_clients:
  - name: "default"            # 客户端名称，在代码中通过此名称获取
    rdbms: "postgresql"        # 数据库类型 (postgresql, mysql, sqlite3)
    host: "127.0.0.1"          # 数据库服务器地址
    port: 5432                 # 数据库服务器端口
    dbname: "mercury"             # 要连接的数据库名
    user: "losangelous"                   # 用户名
    passwd: ""                 # 密码
    is_fast: false             # 是否使用快速模式 (异步)
    number_of_connections: 1   # 连接池中的连接数量
    timeout: -1.0              # SQL 查询超时时间 (秒)，-1 表示无超时
    auto_batch: false          # 是否为 PostgreSQL 启用自动批处理

#
# Redis 客户端配置
#
redis_clients:
  - name: "default"
    host: "127.0.0.1"
    port: 6379
    username: ""
    passwd: ""
    db: 0
    is_fast: false
    number_of_connections: 1
    timeout: -1.0

#
# 应用程序核心配置
#
app:
  # 运行应用的 IO 线程数，0 表示等于 CPU 核心数
  number_of_threads: 1
  
  # Session 相关设置
  enable_session: false
  session_timeout: 0
  session_same_site: "Null"
  session_cookie_key: "JSESSIONID"
  session_max_age: -1
  
  # 静态文件和页面设置
  document_root: "./public"
  home_page: "index.html"
  use_implicit_page: true
  implicit_page: "index.html"
  upload_path: "uploads"
  
  # 允许作为静态文件服务的扩展名列表
  file_types:
    - "gif"
    - "png"
    - "jpg"
    - "js"
    - "css"
    - "html"
    - "ico"
    - "swf"
    - "xap"
    - "apk"
    - "cur"
    - "xml"
    - "webp"
    - "svg"
  
  # 自定义 MIME 类型映射
  mime: {}
  
  # 静态文件位置映射
  locations:
    - default_content_type: "text/plain"
      alias: ""
      is_case_sensitive: false
      allow_all: true
      is_recursive: true
      filters: []
      
  # 连接和性能相关设置
  max_connections: 100000
  max_connections_per_ip: 0
  idle_connection_timeout: 60
  
  # 动态视图 (CSP) 相关设置
  load_dynamic_views: false
  dynamic_views_path:
    - "./views"
  dynamic_views_output_path: ""
  
  # JSON 解析器设置
  json_parser_stack_limit: 1000
  enable_unicode_escaping_in_json: true
  float_precision_in_json:
    precision: 0
    precision_type: "significant"
    
  # 日志系统设置
  log:
    use_spdlog: false
    logfile_base_name: ""
    log_size_limit: 100000000
    max_files: 0
    log_level: "DEBUG"
    display_local_time: false
    
  # 进程和服务器行为设置
  run_as_daemon: false
  handle_sig_term: true
  relaunch_on_error: false
  use_sendfile: true
  use_gzip: true
  use_brotli: false
  static_files_cache_time: 5
  server_header_field: ""
  enable_server_header: true
  enable_date_header: true
  
  # Keep-Alive 和 Pipelining 设置
  keepalive_requests: 0
  pipelining_requests: 0
  
  # 静态文件压缩优化
  gzip_static: true
  br_static: true
  
  # 请求体大小限制
  client_max_body_size: "1M"
  client_max_memory_body_size: "64K"
  client_max_websocket_message_size: "128K"
  
  # 高级网络和请求处理设置
  reuse_port: false
  enabled_compressed_request: false
  enable_request_stream: false

plugins:

custom_config: {}
